apiVersion: batch/v1
kind: Job
metadata:
  name: openshiftpodsupervisor
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: openshift-podsupervisor
    spec:
      containers:
      - name: podsupervisor
        image: podsupervisor:latest
        command: ["bash",  "podsupervisor.sh"]
      restartPolicy: OnFailure    

