apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: openshiftpodsupervisor
spec:
  schedule: "*/1 * * * *"  
  concurrencyPolicy: "Replace" 
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 2 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
        spec:
          containers:
          - name: podsupervisor
            image: podsupervisor:latest
            command: ["bash",  "podsupervisor.sh"]
          restartPolicy: OnFailure

